# Generated by Django 6.0.6 on 2026-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', '🚚 Entrega a domicilio'), ('pickup', '🏪 Paso a recoger (Retiro en punto de venta)')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Lugar donde recogerá el pedido', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Dirección donde se entregará el pedido'),
        ),
    ]
