# Generated by Django 6.0.6 on 2026-06-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_acopio_order_payment_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', '⏳ Pendiente de pago'), ('partial', '💰 Pago parcial'), ('paid', '✅ Pagado')], default='pending', max_length=20),
        ),
    ]
