# Generated by Django 4.2.7 on 2026-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Stock mínimo para activar alerta'),
        ),
    ]
