# Generated by Django 6.0.6 on 2026-06-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_stock_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productor',
            new_name='vendedor',
        ),
        migrations.AddField(
            model_name='product',
            name='precio_compra_productor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio al que el suplidor compró al productor (solo para suplidores)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productor_origen',
            field=models.ForeignKey(blank=True, help_text='Productor original del producto (obligatorio para suplidores)', limit_choices_to={'is_approved': True, 'role': 'productor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_origen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta al consumidor', max_digits=10),
        ),
    ]
