# Generated by Django 6.0.6 on 2026-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_productor_product_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha visto este producto'),
        ),
    ]
