# Generated by Django 6.0.6 on 2026-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('platanos', '🍌 Plátanos'), ('guineos', '🍌 Guineos'), ('arroz', '🍚 Arroz'), ('maiz', '🌽 Maíz'), ('habichuelas', '🫘 Habichuelas'), ('guandules', '🫘 Guandules'), ('yautia_blanca', '🥔 Yautía Blanca'), ('yautia_amarilla', '🥔 Yautía Amarilla'), ('name', '🍠 Ñame'), ('tayota', '🥒 Tayota'), ('auyama', '🎃 Auyama'), ('aguacate', '🥑 Aguacate'), ('miel', '🍯 Miel'), ('leche', '🥛 Leche'), ('queso', '🧀 Queso'), ('carne_res', '🐄 Carne de Res'), ('carne_chivo', '🐐 Carne de Chivo'), ('carne_cerdo', '🐖 Carne de Cerdo'), ('pollo', '🍗 Pollo'), ('huevos', '🥚 Huevos'), ('papa', '🥔 Papa'), ('zanahoria', '🥕 Zanahoria'), ('cebolla', '🧅 Cebolla'), ('ajo', '🧄 Ajo'), ('cilantro', '🌿 Cilantro'), ('oregano', '🌿 Orégano'), ('pimienta', '🌶️ Pimienta'), ('canela', '🪵 Canela'), ('jengibre', '🪵 Jengibre'), ('curcuma', '🪵 Cúrcuma'), ('uvas', '🍇 Uvas'), ('sal', '🧂 Sal'), ('recaito', '🌿 Recaito'), ('apios', '🌿 Apios'), ('malagueta', '🌶️ Malagueta'), ('trigo', '🌾 Trigo')], help_text='Subcategoría específica del producto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('frutas', '🍎 Frutas'), ('verduras', '🥬 Verduras'), ('tuberculos', '🥔 Tubérculos'), ('granos', '🌾 Granos'), ('legumbres', '🫘 Legumbres'), ('hierbas', '🌿 Hierbas Aromáticas'), ('especias', '🌶️ Especias'), ('lacteos', '🥛 Lácteos'), ('carnes', '🍖 Carnes'), ('bebidas', '🥤 Bebidas'), ('condimentos', '🧂 Condimentos')], default='frutas', max_length=30),
        ),
    ]
