# Generated by Django 6.0.6 on 2026-07-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible para venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('frutas', '🍎 Frutas'), ('verduras', '🥬 Verduras'), ('granos', '🌾 Granos'), ('tuberculos', '🥔 Tubérculos'), ('legumbres', '🫘 Legumbres'), ('cereal', '🌾 Cereal'), ('lacteos', '🧀 Lácteos'), ('viveres', '🍌 Viveres'), ('viandas', '🍠 Viandas'), ('bebidas', '🧃 Bebidas'), ('condimentos', '🌶️ Condimentos'), ('especias', '🌿 Especias'), ('hierbas_aromaticas', '🌱 Hierbas aromáticas'), ('mariscos', '🦐 Mariscos'), ('moluscos', '🐚 Moluscos'), ('embutidos_carnes', '🥩 Embutidos y Carnes')], default='frutas', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Subcategoría específica del producto', max_length=50, null=True, verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('lb', 'Libra (lb)'), ('L', 'Litro (L)'), ('gal', 'Galón (gal)'), ('doc', 'Docena (doc)'), ('pt', 'Pinta (pt)'), ('tza', 'Taza (tza)'), ('oz', 'Onza (oz)'), ('kg', 'Kilogramo (kg)'), ('qq', 'Kilo (quintal) (qq)')], default='lb', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
