# Generated by Django 6.0.6 on 2026-07-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_options_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('frutas', '🍎 Frutas'), ('verduras', '🥬 Verduras'), ('granos', '🌾 Granos'), ('tuberculos', '🥔 Tubérculos'), ('legumbres', '🫘 Legumbres'), ('cereal', '🌾 Cereal'), ('lacteos', '🧀 Lácteos'), ('viveres', '🍌 Viveres'), ('viandas', '🍠 Viandas'), ('bebidas', '🧃 Bebidas'), ('condimentos', '🌶️ Condimentos'), ('especias', '🌿 Especias'), ('hierbas_aromaticas', '🌱 Hierbas aromáticas'), ('mariscos', '🦐 Mariscos'), ('moluscos', '🐚 Moluscos'), ('embutidos_carnes', '🥩 Embutidos y Carnes'), ('panaderia', '🍞 Panadería y Repostería'), ('abarrotes', '🥫 Abarrotes'), ('cafe_te', '☕ Café y Té'), ('cacao_chocolate', '🍫 Cacao y Chocolate'), ('hongos_setas', '🍄 Hongos y Setas'), ('pescados', '🐟 Pescados'), ('aceites_grasas', '🫒 Aceites y Grasas'), ('endulzantes', '🍯 Endulzantes')], default='frutas', max_length=50, verbose_name='Categoría'),
        ),
    ]
