# Generated by Django 6.0.6 on 2026-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='otros', help_text='Subcategoría específica del producto (obligatorio)', max_length=50, verbose_name='Subcategoría'),
            preserve_default=False,
        ),
    ]
