# Generated by Django 4.2.7 on 2026-06-04 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('price', 'Precio abusivo'), ('quality', 'Calidad del producto'), ('delivery', 'Problema con entrega'), ('other', 'Otro')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('investigating', 'En investigación'), ('resolved', 'Resuelto'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL)),
                ('complained_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('old_status', models.CharField(choices=[('pending', 'Pendiente'), ('investigating', 'En investigación'), ('resolved', 'Resuelto'), ('rejected', 'Rechazado')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('investigating', 'En investigación'), ('resolved', 'Resuelto'), ('rejected', 'Rechazado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='complaints.complaint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
