# Generated by Django 6.0.6 on 2026-06-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('automatico', 'Automático diario'), ('manual', 'Punto de restauración manual'), ('previo_actualizacion', 'Previo a actualización')], max_length=30)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('en_proceso', 'En proceso')], default='en_proceso', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Antes de actualizar precios', max_length=200)),
            ],
            options={
                'verbose_name': 'Historial de Backup',
                'verbose_name_plural': 'Historial de Backups',
                'ordering': ['-fecha'],
            },
        ),
    ]
