# Generated by Django 6.0.6 on 2026-06-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='nombre_archivo',
            field=models.CharField(blank=True, help_text='Nombre del archivo de backup', max_length=200),
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='estado',
            field=models.CharField(choices=[('exitoso', '✅ Exitoso'), ('fallido', '❌ Fallido'), ('en_proceso', '🔄 En proceso')], default='en_proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='tipo',
            field=models.CharField(choices=[('automatico', '🤖 Automático diario'), ('manual', '👤 Punto de restauración manual'), ('previo_actualizacion', '⚠️ Previo a actualización')], max_length=30),
        ),
    ]
