# Generated by Django 6.0.6 on 2026-06-09 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_backuphistory_nombre_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('excelente', '🌟 Excelente - Productor ejemplar'), ('bueno', '👍 Bueno - Cumple con lo pactado'), ('regular', '⚠️ Regular - Presenta quejas ocasionales'), ('malo', '👎 Malo - Múltiples quejas justificadas'), ('critico', '🚨 Crítico - Riesgo para consumidores')], default='bueno', max_length=20)),
                ('comentario', models.TextField(help_text='Justificación del nivel asignado por ONPECO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(limit_choices_to={'role': 'productor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reputacion_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reputación',
                'verbose_name_plural': 'Reputaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
