# Generated by Django 6.0.6 on 2026-07-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_reputacion'),
        ('marketplace', '0009_categoriaproducto_subcategoriaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto relacionado con la denuncia (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='marketplace.product'),
        ),
    ]
