# Generated by Django 6.0.6 on 2026-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='Si es True, el perfil público es visible para todos. Si es False, solo el productor y ONPECO pueden verlo.'),
        ),
    ]
