# Generated by Django 6.0.6 on 2026-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_profile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputacion_actual',
            field=models.CharField(blank=True, choices=[('excelente', '🌟 Excelente - Productor ejemplar'), ('bueno', '👍 Bueno - Cumple con lo pactado'), ('regular', '⚠️ Regular - Presenta quejas ocasionales'), ('malo', '👎 Malo - Múltiples quejas justificadas'), ('critico', '🚨 Crítico - Riesgo para consumidores')], default='bueno', help_text='Nivel de reputación asignado por ONPECO', max_length=20, null=True),
        ),
    ]
