# Generated by Django 6.0.6 on 2026-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_reputacion_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña al iniciar sesión (contraseña temporal)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('productor', 'Productor'), ('consumidor', 'Consumidor'), ('suplidor', 'Suplidor'), ('regulador', 'Regulador'), ('acopio', 'Centro de Acopio')], default='consumidor', max_length=20),
        ),
    ]
