# Generated by Django 6.0.6 on 2026-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.FloatField(help_text='Tamaño en KB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Historial de Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
