# Generated by Django 6.0.6 on 2026-06-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1'), (2, '⭐⭐ 2'), (3, '⭐⭐⭐ 3'), (4, '⭐⭐⭐⭐ 4'), (5, '⭐⭐⭐⭐⭐ 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('consumidor', models.ForeignKey(limit_choices_to={'role': 'consumidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_hechas', to=settings.AUTH_USER_MODEL)),
                ('productor', models.ForeignKey(limit_choices_to={'role': 'productor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('productor', 'consumidor')},
            },
        ),
    ]
