# apps/marketplace/constants.py

CATEGORIAS = [
    ('frutas', '🍎 Frutas'),
    ('verduras', '🥬 Verduras'),
    ('granos', '🌾 Granos'),
    ('tuberculos', '🥔 Tubérculos'),
    ('legumbres', '🫘 Legumbres'),
    ('cereal', '🌾 Cereal'),
    ('lacteos', '🧀 Lácteos'),
    ('viveres', '🍌 Viveres'),
    ('viandas', '🍠 Viandas'),
    ('bebidas', '🧃 Bebidas'),
    ('condimentos', '🌶️ Condimentos'),
    ('especias', '🌿 Especias'),
    ('hierbas_aromaticas', '🌱 Hierbas aromáticas'),
    ('mariscos', '🦐 Mariscos'),
    ('moluscos', '🐚 Moluscos'),
    ('embutidos_carnes', '🥩 Embutidos y Carnes'),
    ('panaderia', '🍞 Panadería y Repostería'),
    ('abarrotes', '🥫 Abarrotes'),
    ('cafe_te', '☕ Café y Té'),
    ('cacao_chocolate', '🍫 Cacao y Chocolate'),
    ('hongos_setas', '🍄 Hongos y Setas'),
    ('pescados', '🐟 Pescados'),
    ('aceites_grasas', '🫒 Aceites y Grasas'),
    ('endulzantes', '🍯 Endulzantes'),
]

SUBCATEGORIAS = {
    'frutas': [
        ('citricos', '🍊 Cítricos'),
        ('tropicales', '🥭 Tropicales'),
        ('bayas', '🍓 Bayas'),
        ('otras_frutas', '🍇 Otras frutas'),
    ],
    'verduras': [
        ('hojas_verdes', '🥬 Hojas verdes'),
        ('raices', '🥕 Raíces'),
        ('flores', '🥦 Flores'),
        ('otras_verduras', '🌽 Otras verduras'),
    ],
    'granos': [
        ('arroz', '🍚 Arroz'),
        ('maiz', '🌽 Maíz'),
        ('trigo', '🌾 Trigo'),
        ('avena', '🌾 Avena'),
        ('otros_granos', '📦 Otros granos'),
    ],
    'tuberculos': [
        ('papa', '🥔 Papa'),
        ('yuca', '🌱 Yuca'),
        ('batata', '🍠 Batata'),
        ('name', '🌿 Ñame'),
        ('malanga', '🌿 Malanga'),
        ('otros_tuberculos', '📦 Otros tubérculos'),
    ],
    'legumbres': [
        ('frijoles', '🫘 Frijoles'),
        ('lentejas', '🫘 Lentejas'),
        ('garbanzos', '🫘 Garbanzos'),
        ('habichuelas', '🫘 Habichuelas'),
        ('guandules', '🫘 Guandules'),
        ('otras_legumbres', '📦 Otras legumbres'),
    ],
    'cereal': [
        ('arroz', '🍚 Arroz'),
        ('maiz', '🌽 Maíz'),
        ('trigo', '🌾 Trigo'),
        ('avena', '🌾 Avena'),
        ('cebada', '🌾 Cebada'),
        ('otros_cereales', '📦 Otros cereales'),
    ],
    'lacteos': [
        ('leche', '🥛 Leche'),
        ('queso', '🧀 Queso'),
        ('yogurt', '🫙 Yogurt'),
        ('mantequilla', '🧈 Mantequilla'),
        ('boruga', '🧀 Boruga'),
        ('nata', '🥛 Nata'),
        ('otros_lacteos', '📦 Otros lácteos'),
    ],
    'viveres': [
        ('platano', '🍌 Plátano'),
        ('guineo', '🍌 Guineo'),
        ('relleno', '🍌 Relleno'),
        ('topocho', '🍌 Topocho'),
        ('otros_viveres', '📦 Otros viveres'),
    ],
    'viandas': [
        ('name', '🌿 Ñame'),
        ('malanga', '🌿 Malanga'),
        ('yautia', '🌿 Yautía'),
        ('batata', '🍠 Batata'),
        ('otras_viandas', '📦 Otras viandas'),
    ],
    'bebidas': [
        ('jugos_naturales', '🧃 Jugos naturales'),
        ('refrescos', '🥤 Refrescos'),
        ('agua', '💧 Agua'),
        ('bebidas_lacteas', '🥛 Bebidas lácteas'),
        ('otras_bebidas', '🧃 Otras bebidas'),
    ],
    'condimentos': [
        ('sal', '🧂 Sal'),
        ('pimienta', '🌶️ Pimienta'),
        ('comino', '🌶️ Comino'),
        ('oregano_seco', '🌿 Orégano seco'),
        ('aji', '🌶️ Ají'),
        ('otros_condimentos', '📦 Otros condimentos'),
    ],
    'especias': [
        ('canela', '🌿 Canela'),
        ('clavo', '🌿 Clavo'),
        ('nuez_moscada', '🌿 Nuez moscada'),
        ('jengibre', '🌿 Jengibre'),
        ('curcuma', '🌿 Cúrcuma'),
        ('otras_especias', '📦 Otras especias'),
    ],
    'hierbas_aromaticas': [
        ('cilantro', '🌿 Cilantro'),
        ('perejil', '🌿 Perejil'),
        ('oregano', '🌿 Orégano'),
        ('menta', '🌿 Menta'),
        ('romero', '🌿 Romero'),
        ('albahaca', '🌿 Albahaca'),
        ('otras_hierbas', '🌿 Otras hierbas'),
    ],
    'mariscos': [
        ('camarones', '🦐 Camarones'),
        ('langosta', '🦞 Langosta'),
        ('cangrejo', '🦀 Cangrejo'),
        ('calamar', '🦑 Calamar'),
        ('pulpo', '🐙 Pulpo'),
        ('lambi', '🐚 Lambi'),
        ('vacalao', '🐟 Vacalao'),
        ('otros_mariscos', '📦 Otros mariscos'),
    ],
    'moluscos': [
        ('ostras', '🦪 Ostras'),
        ('mejillones', '🐚 Mejillones'),
        ('almejas', '🐚 Almejas'),
        ('caracoles', '🐚 Caracoles'),
        ('otros_moluscos', '📦 Otros moluscos'),
    ],
    'embutidos_carnes': [
        ('salami', '🥩 Salami'),
        ('jamon', '🥩 Jamón'),
        ('chuletas_con_hueso', '🍖 Chuletas con hueso'),
        ('chuletas_sin_hueso', '🥩 Chuleta sin hueso'),
        ('longaniza', '🌭 Longaniza'),
        ('molida', '🥩 Molida'),
        ('salchichas', '🌭 Salchichas'),
        ('costillitas', '🍖 Costillitas'),
        ('arenque', '🐟 Arenque'),
        ('res', '🥩 Res'),
        ('pollo', '🍗 Pollo'),
        ('cerdo', '🥩 Cerdo'),
        ('pavo', '🦃 Pavo'),
        ('chivo', '🐐 Chivo'),
        ('guineas', '🦃 Guineas'),
        ('otros_embutidos', '📦 Otros embutidos'),
    ],
    'panaderia': [
        ('pan', '🍞 Pan'),
        ('bizcochos', '🎂 Bizcochos'),
        ('pasteles', '🧁 Pasteles'),
        ('reposteria', '🍰 Repostería'),
        ('otros_panaderia', '📦 Otros productos de panadería'),
    ],
    'abarrotes': [
        ('pastas', '🍝 Pastas'),
        ('enlatados', '🥫 Enlatados'),
        ('salsas', '🥫 Salsas'),
        ('vinagres', '🧪 Vinagres'),
        ('otros_abarrotes', '📦 Otros abarrotes'),
    ],
    'cafe_te': [
        ('cafe_grano', '☕ Café en grano'),
        ('cafe_molido', '☕ Café molido'),
        ('te', '🍵 Té'),
        ('infusiones', '🌿 Infusiones'),
        ('otros_cafe_te', '📦 Otros cafés y tés'),
    ],
    'cacao_chocolate': [
        ('cacao_grano', '🍫 Cacao en grano'),
        ('cacao_pasta', '🍫 Pasta de cacao'),
        ('chocolate_artesanal', '🍫 Chocolate artesanal'),
        ('otros_cacao', '📦 Otros productos de cacao'),
    ],
    'hongos_setas': [
        ('champiñones', '🍄 Champiñones'),
        ('portobello', '🍄 Portobello'),
        ('shiitake', '🍄 Shiitake'),
        ('otros_hongos', '📦 Otros hongos'),
    ],
    'pescados': [
        ('pescado_fresco', '🐟 Pescado fresco'),
        ('pescado_salado', '🐟 Pescado salado'),
        ('pescado_ahumado', '🐟 Pescado ahumado'),
        ('otros_pescados', '📦 Otros pescados'),
    ],
    'aceites_grasas': [
        ('aceite_vegetal', '🫒 Aceite vegetal'),
        ('aceite_oliva', '🫒 Aceite de oliva'),
        ('manteca', '🧈 Manteca'),
        ('grasa_cerdo', '🥓 Grasa de cerdo'),
        ('otros_aceites', '📦 Otros aceites y grasas'),
    ],
    'endulzantes': [
        ('azucar', '🍬 Azúcar'),
        ('panela', '🍯 Panela'),
        ('miel', '🍯 Miel de abeja'),
        ('otros_endulzantes', '📦 Otros endulzantes'),
    ],
}

UNIDADES = [
    ('lb', 'Libra (lb)'),
    ('L', 'Litro (L)'),
    ('gal', 'Galón (gal)'),
    ('doc', 'Docena (doc)'),
    ('pt', 'Pinta (pt)'),
    ('tza', 'Taza (tza)'),
    ('oz', 'Onza (oz)'),
    ('kg', 'Kilogramo (kg)'),
    ('qq', 'Kilo (quintal) (qq)'),
]

def get_subcategorias(categoria):
    """Retorna las subcategorías para una categoría dada"""
    return SUBCATEGORIAS.get(categoria, [])

def get_unidad_display(unit_key):
    """Retorna el nombre completo de una unidad por su clave"""
    for key, value in UNIDADES:
        if key == unit_key:
            return value
    return unit_key